### ISSUE TITLE
Parameter substitution case

### ISSUE THREAD

**Issue by mads-hartmann** [tree-sitter/tree-sitter-bash#10]
Not sure if this is covered by #9 but I found a parameter substitution case in one of my Bash files that the parser doesn't like. A minimal example is the following:

```bash
echo ${var1#*#}
```

It will remove everything from the beginning of `var1` until it reaches an `#`.  Here's a valid example

```bash
var1=foobar-#123
echo ${var1#*#}
```

**Comment by maxbrunsfeld** [comment]
Ah yeah, it's probably getting confused because comments start with `#`. Bash...
