### ISSUE TITLE
comments are missing newlines

### ISSUE THREAD

**Issue by milahu** [tree-sitter/tree-sitter-bash#108]
repro

```js
const TreeSitter = require('tree-sitter');
const TreeSitterBash = require('tree-sitter-bash');

const parser = new TreeSitter();
parser.setLanguage(TreeSitterBash);

const sourceCode = `\
#!/usr/bin/env bash

# hello

# world

main() {
  echo "hello world"
}

main
`;
const tree = parser.parse(sourceCode);

for (const node of tree.rootNode.children) {
  console.dir({ type: node.type, text: node.text });
}
```

input

```bash
#!/usr/bin/env bash

# hello

# world

main() {
  echo "hello world"
}

main
```

actual vs expected

```diff
-{ type: 'comment', text: '#!/usr/bin/env bash' }
+{ type: 'comment', text: '#!/usr/bin/env bash\n' }
+{ type: '\n', text: '\n' }
-{ type: 'comment', text: '# hello' }
+{ type: 'comment', text: '# hello\n' }
+{ type: '\n', text: '\n' }
-{ type: 'comment', text: '# world' }
+{ type: 'comment', text: '# world\n' }
+{ type: '\n', text: '\n' }
 { type: 'function_definition', text: 'main() {\n  echo "hello world"\n}' }
 { type: '\n', text: '\n\n' }
 { type: 'command', text: 'main' }
 { type: '\n', text: '\n' }
```

**Comment by ahlinc** [comment]
![image](https://github.com/tree-sitter/tree-sitter-bash/assets/14666676/f792376b-6755-4e30-91de-186aa1bc992f)

![image](https://github.com/tree-sitter/tree-sitter-bash/assets/14666676/daf463b8-2907-429d-84e5-0b21e1f241ec)

Current output looks clear, comments are not multiline heredocs and shouldn't capture trailing `\n` bytes.

@amaanq May be it makes sense to close this?

**Comment by milahu** [comment]
thanks for the screenshot of text...

current output of my script is

```
{ type: 'comment', text: '#!/usr/bin/env bash' }
{ type: 'comment', text: '# hello' }
{ type: 'comment', text: '# world' }
{ type: 'function_definition', text: 'main() {\n  echo "hello world"\n}'}
{ type: 'command', text: 'main' }
```

the previous output was better for my use-case

```
{ type: 'comment', text: '#!/usr/bin/env bash' }
{ type: 'comment', text: '# hello' }
{ type: 'comment', text: '# world' }
{ type: 'function_definition', text: 'main() {\n  echo "hello world"\n}' }
{ type: '\n', text: '\n\n' }
{ type: 'command', text: 'main' }
{ type: '\n', text: '\n' }
```

expected result: tree-sitter should produce a syntax tree with whitespace nodes

this is required for lossless source-to-source compilers
but then, the main use-case of tree-sitter parsers is syntax-highlighting
where whitespace nodes are not needed, and only would waste memory

if anyone needs a "tree with whitespace", probably he should fork this parser

**Comment by ahlinc** [comment]
> if anyone needs a "tree with whitespace", probably he should fork this parser

First of all, the exposed  `\n` symbols were visible in a few cases and not in all cases were they may occur,  so building something precise and reliable on that parser mistake doesn't look reliable too.

It's not required to close and rollback the mistake in the parser, precisely capturing mix of spaces and tabs and LF symbols more reliable when traversing a tree and storing a previous terminal node location (anonymous or named) and calculating a new bytes range between such terminal nodes, after that it's possible to use such range to extract a real sequence of space characters from a related source text for further analysis and building transformations over it.

/cc: @milahu
