### ISSUE TITLE
expansion with whitespace should error: ${one two}

### ISSUE THREAD

**Issue by verhovsky** [tree-sitter/tree-sitter-bash#113]
This is not a valid `${expansion}` 

```sh
$ one="some string"
$ echo "${one two}"
-bash: ${one two}: bad substitution
```

but tree-sitter-bash parses the "`two`" as a `word` when (as I understand it) it should be an ERROR

```
"${one two}"
```

```
program [0, 0] - [1, 0]
  command [0, 0] - [0, 12]
    name: command_name [0, 0] - [0, 12]
      string [0, 0] - [0, 12]
        expansion [0, 1] - [0, 11]
          variable_name [0, 3] - [0, 6]
          word [0, 7] - [0, 10]
```

https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html

**Comment by ahlinc** [comment]
Current output:
![image](https://github.com/tree-sitter/tree-sitter-bash/assets/14666676/d680b5ba-ee46-4608-aad2-41d3070b4cbc)

The word `two` was lost during error recovery what looks like a new issue.

**Comment by amaanq** [comment]
this seems expected now - because before expansions were too "loose", and now we get an error, so this issue is resolved

However, is it okay that two got lost?

**Comment by ahlinc** [comment]
@amaanq No it's not okay, usually it signs about an issue in external scanner.
Please reopen this issue.

**Comment by amaanq** [comment]
shouldn't it be a new issue?

**Comment by ahlinc** [comment]
> shouldn't it be a new issue?

I think it's ok to track it here.

**Comment by amaanq** [comment]
Seems like it's not lost now during error recovery, not sure when that might've happened

<img width="332" alt="image" src="https://github.com/tree-sitter/tree-sitter-bash/assets/29718261/fab5cb47-bdec-49b4-b9a1-93a428a8d216">
