### ISSUE TITLE
Parser does not handle brace expansion for arrays {1..10} correctly

### ISSUE THREAD

**Issue by Wilfred** [tree-sitter/tree-sitter-bash#119]
The following programs have the same parse tree, but mean different things:

```
echo {1..10}
echo {1..10
```

The first is an array, the second is a literal word `{1..10`.

**Comment by amaanq** [comment]
Hey @Wilfred can you try out master? And let me know if there are cases for brace expansions I didn't cover that fail to parse, thanks!

**Comment by amaanq** [comment]
Anytime 😁
