### ISSUE TITLE
>&2 causes the rest of the file to be a quoted string

### ISSUE THREAD

**Issue by classabbyamp** [tree-sitter/tree-sitter-bash#125]
Using neovim 0.7.0 on void linux, with the latest treesitter & grammars installed.

When treesitter highlighting is enabled, the `>&2` in `printf >&2 "something"` causes treesitter to fail to parse the next quoted string properly, leading to an erroneous quote imbalance and the rest of the file to be highlighted like a quoted string.

Treesitter highlighting enabled:
![image](https://user-images.githubusercontent.com/5366828/172559446-68aab65c-2bfe-4d1c-8cd1-6e34565eedd9.png)

Disabled:
![image](https://user-images.githubusercontent.com/5366828/172559629-25b49eec-eeb1-4675-a1ed-66b04372420d.png)

**Comment by black-desk** [comment]
For more information check <https://github.com/tree-sitter/tree-sitter-bash/issues/140#issuecomment-1366345010>

**Comment by Ordoviz** [comment]
duplicate of #72
