### ISSUE TITLE
Heredoc delimiter with "_" is not correctly parsed

### ISSUE THREAD

**Issue by ppwwyyxx** [tree-sitter/tree-sitter-bash#129]
![9UMWGFK23ipumek](https://user-images.githubusercontent.com/1381301/185763105-4a7e43be-e2ed-47ba-b8f8-8b5349f44494.png)

I expect `func2` to be highlighted similar to `func1`.

This issue looks related to https://github.com/tree-sitter/tree-sitter-bash/pull/47

**Comment by freddylist** [comment]
I've also run into this issue.

Without leading underscore delimiter, syntax highlighting is of course fine:
![image](https://user-images.githubusercontent.com/51757856/196240028-7814c8f6-de13-4d3b-ab6b-d334ecd105fb.png)

With leading underscore delimiter and an apostrophe in the heredoc, syntax highlighting is completely borked:
![image](https://user-images.githubusercontent.com/51757856/196240141-f17c1fac-b58a-4004-90c0-e422474d221c.png)
(Single apostrophe can happen when contractions such as "it's" and "should've" appear in the heredoc.)

I also see that whether or not the delimiter has a leading underscore, if the first word is `$SOME_VARIABLE`, the syntax highlighting for that line is incorrect:
![image](https://user-images.githubusercontent.com/51757856/196240852-30d83499-cf5a-4d56-8e2e-4c49b88785cb.png)
![image](https://user-images.githubusercontent.com/51757856/196241053-df1150e2-0c2e-46dd-93c5-cb5529fbd505.png)
Dunno if this is a separate issue or not.

**Comment by amaanq** [comment]
This works on master for me
