### ISSUE TITLE
Bad Parsing of here string with file descriptor

### ISSUE THREAD

**Issue by rasmuspeders1** [tree-sitter/tree-sitter-bash#154]
It looks like highlighting breaks after using here string with a file descriptor.
It works fine with just the here string `<<<` but `3<<<` breaks it.

Example of problem:

 ![2023-03-13T11:13:30,654452625+01:00](https://user-images.githubusercontent.com/1898960/224673157-ea448ab1-04e1-426b-955f-4fb18728a544.png)

**Comment by verhovsky** [comment]
```sh
#/bin/bash

ENTRIES= "a=1 b=2
a=2 b=3"

while read -u 3 entry; do
  echo $entry
done 3<<<"$ENTRIES"

echo: "some stuff"

printf "%s" some more stuff
```

**Comment by rasmuspeders1** [comment]
Coming back to this. I think you are right. This looks fixed on master. I have no problems today. Closing this again.
