### ISSUE TITLE
Question: The purpose and consequences of \n nodes

### ISSUE THREAD

**Issue by Xophmeister** [tree-sitter/tree-sitter-bash#155]
The Bash grammar emits anonymous `\n` sibling nodes. Anecdotally, these appear to occur -- if you'll forgive the hand-waving -- after a "non-inlined statement". That is, they seem to indicate where a line break is necessary (but not sufficient).

The problem we're having is that this obviously has a physical representation; a line break. Is there any reason why an abstract representation (i.e., some parent node) wouldn't serve the same purpose? (To rephrase: If we were to work on this, for our purposes, could it have significant repercussions for others? We'd prefer to contribute to `tree-sitter-bash`, rather than maintaining our own fork.)

Examples:

```bash
echo foo
```
![echo foo](https://user-images.githubusercontent.com/384987/225026472-5d401f2c-2b0f-44cb-a374-b724ea0fdd2b.svg)

```bash
if some_command --option; then echo foo; fi
```

![if one-liner](https://user-images.githubusercontent.com/384987/225027502-42ce3666-4a38-4b2e-835c-51de43fbe278.svg)

```bash
if some_command --option; then
  echo foo
fi
```

![if w/ inline then](https://user-images.githubusercontent.com/384987/225026833-4abdad0e-0e0d-42ad-be91-abfbcce04959.svg)

```bash
if some_command --option
then
  echo foo
fi
```

![exploded if](https://user-images.githubusercontent.com/384987/225027918-71f5544a-fe46-4fde-a92a-f9c07c0d84ee.svg)

Interestingly, `\n` nodes are not inserted after comments (see #108):

```bash
# comment
echo foo
```

![comment w/o newline](https://user-images.githubusercontent.com/384987/225028510-04731d1e-d90f-47fb-b57a-7ab6ac4e42ee.svg)

Presumably this is because comments _must_ end with a new line, so adding an `\n` node would be redundant.

**Comment by ahlinc** [comment]
@amaanq this was fixed in:
* #198
