### ISSUE TITLE
Cant Install tree-sitter-bash for some reason

### ISSUE THREAD

**Issue by fislysandi** [tree-sitter/tree-sitter-bash#158]
im using debian wsl with gnu guix, i was configuring my neovim and when i open up a bash script and TS tries to install tree-sitter-bash it fails to compile it and it gives me this error
![WindowsTerminal_nQK02y1uK0](https://user-images.githubusercontent.com/45166203/226428751-9fc9f9be-dfd1-4118-b86d-c855ab527f9e.png)
![WindowsTerminal_NclWyfB45D](https://user-images.githubusercontent.com/45166203/226428753-7db9a868-3d95-44d6-98b3-001463ccfe38.png)
![WindowsTerminal_sqsrliovwx](https://user-images.githubusercontent.com/45166203/226428771-c23690ee-92ff-45fe-a178-4082aaca24c8.png)

you can clone my repo to have a closer look at https://github.com/fislysandi/guix-kickstart its located under guix-config/dotfiles/nvim

c , lua , etc installs just fine but for some reason it has issues with bash.

im noticing a lot of depreciated messages. related to x11? why is it even here?

**Comment by amaanq** [comment]
belongs in nvim-treesitter
