### ISSUE TITLE
Heredoc redirect to file is not handled properly

### ISSUE THREAD

**Issue by achekulaev** [tree-sitter/tree-sitter-bash#16]
Example:

```bash
#!/usr/bin/env bash

tmpfile="/tmp/fix-smb.reg"

cat <<EOF > $tmpfile
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management]
"LargeSystemCache"=dword:00000001

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\LanmanServer\Parameters]
"Size"=dword:00000003
EOF
```

The heredoc redirect above is valid and should not be reported as an issue.

**Comment by maxbrunsfeld** [comment]
🙏  Thanks for this great set of issues @achekulaev.

**Comment by achekulaev** [comment]
No probs! :) Hopefully I don't spam you too much with those. I'm just trying to get bash server based on tree-sitter-bash to work with my huge Bash script, which reports over a hundred errors right now :)

**Comment by mads-hartmann** [comment]
@achekulaev If you want to try fixing some of these issues here's a short guide :)

```
npm install
npm run build
```

Now open one of the files in the `corpus` folder and create a minimal test case like this (you can probably make it even smaller)

```bash

====================================
Heredoc redirects
====================================

#!/usr/bin/env bash

tmpfile="/tmp/fix-smb.reg"

cat <<EOF > $tmpfile
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management]
"LargeSystemCache"=dword:00000001

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\LanmanServer\Parameters]
"Size"=dword:00000003
EOF

---

```

Now run `npm test`. You should see that the test failed as we're expected the AST to be empty (we have nothing after the three `-`'es`).

Now edit the grammar in `./grammar.js` and run `npm run build && npm test` until you're happy with the output. Copy it into the test and you're done :)
