### ISSUE TITLE
Wrong parsing for `${!#}`

### ISSUE THREAD

**Issue by ppwwyyxx** [tree-sitter/tree-sitter-bash#160]
In bash, `${!#}` means the last argument passed to the script.
However, it's not correctly parsed:
![2023-03-26_07-29](https://user-images.githubusercontent.com/1381301/227782589-010cf4e1-6bc9-4e37-8625-2d875b0ca641.png)

Source code: 
```
#!/bin/bash -v

last_argument=${!#}
ls 
# a comment
```

**Comment by Thanatermesis** [comment]
Same problem here, with a similar variable replacement:

```bash
 display="${display%|*}"
```
It makes the syntax broken for the rest of the file
