### ISSUE TITLE
Parse failing if there is no newline at the end of script, but TSPlayground shows no error

### ISSUE THREAD

**Issue by MostHated** [tree-sitter/tree-sitter-bash#162]
I am having an issue where parse is failing unless I add a blank newline to the end of the script.

Without it, I get the following:

```bash
  ...
  (ERROR [23, 0] - [23, 5]
    (identifier [23, 0] - [23, 1])
    (identifier [23, 4] - [23, 5])))
/mnt/x/cyber/test/arc_cases_test.cy	0 ms	(ERROR [23, 0] - [23, 5])
```
but opening the script and examining with TSPlayground, it shows no issue:

![](https://img.instance.id/hPlGHZlp0f6X/direct)

Then, if I add a newline to the end and run parse again, I get this and everything is fine:

```bash
  ...  
  (local_declaration [23, 0] - [23, 5]
    name: (identifier [23, 0] - [23, 1])
    expression: (identifier [23, 4] - [23, 5])))
```

The fact TSPlayground is showing everything is fine and as expected, I can't quite figure out if this is an issue with my grammar and it is just an adjustment I need to make, or something more than that?

**Comment by amaanq** [comment]
Doens't look like bash

**Comment by MostHated** [comment]
Yeah, it was not. Why in the world did I post this here? My apologies.
