### ISSUE TITLE
Bash case pattern with escaped space not rendered correctly in Neovim

### ISSUE THREAD

**Issue by madjxatw** [tree-sitter/tree-sitter-bash#165]
Treesitter doesn't highlight the text correctly where bash case pattern with escaped space is used.

![screenshot_20230410-064511Z](https://user-images.githubusercontent.com/6035833/230864636-dcc0816f-d424-448d-a2ec-7b6479111b37.png)

**Comment by verhovsky** [comment]
```sh
case "$1" in
  foobar)
    echo "$1"
    ;;
  foo\ bar)
    echo "$1"
    ;;
  *)
    ;;
esac
```

Looks like the `\ ` in `foo\ bar` isn't escaping the space.

**Comment by madjxatw** [comment]
> ```shell
> case "$1" in
>   foobar)
>     echo "$1"
>     ;;
>   foo\ bar)
>     echo "$1"
>     ;;
>   *)
>     ;;
> esac
> ```
> 
> Looks like the `\ ` in `foo\ bar` isn't escaping the space.

The syntax is illegal, but not highlighted correctly.

**Comment by tmillr** [comment]
> ```shell
> ```shell
> case "$1" in
>   foobar)
>     echo "$1"
>     ;;
>   foo\ bar)
>     echo "$1"
>     ;;
>   *)
>     ;;
> esac
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> Looks like the \  in foo\ bar isn't escaping the space.
> 
> The syntax is legal, but not handled properly, making all following text  rendered in wrong color.  Currently I have to use if-else instead.
> ```

You can continue using the case statement, just replace `foo\ bar)` with `foo[ ]bar)` or `foo' 'bar)`.

**Comment by tmillr** [comment]
This issue isn't just limited to case statements. See #169
