### ISSUE TITLE
Unknown syntax should not break the syntax

### ISSUE THREAD

**Issue by Thanatermesis** [tree-sitter/tree-sitter-bash#172]
Sometimes there's special variable replacement that breaks the syntax of the entire file, for example: 

```bash
display="${display%|*}"
```

But it happens also with other code, on this case unknown syntax, for example this is a piece of code made to work compatible in the case the shell is ZSH: 

```zsh
        if [[ -n "$ZSH_VERSION" ]] ; then
            if [[ ! -n "${(P)_var}" ]] ; then
                el_error "Variable '$_var' is not set, func: ${FUNCNAME[1]}"
```

Where the "${(P)_var}" makes the syntax being broken in the rest of the file too

**Comment by pr3c0g** [comment]
I'm facing the same issue.

Here's an example I quickly wrote with the same case as OP:
![image](https://user-images.githubusercontent.com/11090205/236690324-191e6b3b-56d5-4050-a3f5-4bfe22e2b284.png)

After disabling tree-sitter syntax highlighting:
![image](https://user-images.githubusercontent.com/11090205/236690375-f1e73ab3-c0a5-435d-8c7a-5b238bdbf304.png)

I'm using neovim 0.9, not sure if there's anything else relevant for this issue.
The syntax highlighting breaks at exactly the `${1%%|*}` part.

**Comment by Thanatermesis** [comment]
@pr3c0g how do you do for disabling the tree-sitter syntax? I will need to do that to my "sh" filetypes otherwise I will not be able to use them

**Comment by pr3c0g** [comment]
In this case I just disabled via `:TSDisable highlight` but that will only work for the current buffer. For permanently disabling it, you have to change the configuration of nvim-treesitter, removing bash from the `ensured_installed`.

You can run `:TSConfigInfo` to check which ones are auto installed, it shows at the top for me:
![image](https://user-images.githubusercontent.com/11090205/236693010-6afb8705-f225-4128-a1bb-6cdf15187007.png)

**Comment by Thanatermesis** [comment]
More syntax problems on bash, for this case:

```bash
                cat > "$script" -- <<EOF
#!/bin/bash
echo "LANG=$LANG" > /etc/default/locale
if ! grep -qs "^${LANG} ${LANG#*.}$" /etc/locale.gen ; then
    sed -i -e "s|# ${LANG} ${LANG#*.}|${LANG} ${LANG#*.}|" /etc/locale.gen
fi

echo more commands in heredocs...
EOF

echo "heredocs finished, continuing with normal code:"
chmod +x "$script"
echo running bash "$script"...
```

On which the issue is i think for ``` ${LANG#*.}$" ```

**Comment by pr3c0g** [comment]
Some more info that I found out,

In my case, tree-sitter is failing to parse the unescaped pipe, even though it's valid shell syntax. However, escaping the pipe not only makes tree-sitter work correctly, it's still the same valid shell syntax:

![image](https://github.com/tree-sitter/tree-sitter-bash/assets/11090205/614dd77c-fca8-448c-b187-6f29bb1f6cde)

unescaped pipe:

![image](https://github.com/tree-sitter/tree-sitter-bash/assets/11090205/12ee66ae-6b6e-480b-8c3e-508fba1347cc)

escaped pipe:

![image](https://github.com/tree-sitter/tree-sitter-bash/assets/11090205/8dc4f2a7-0653-4b43-9c7a-871be1d9312e)

**Comment by amaanq** [comment]
The first example should be fixed (pipe in variable expansion, but the second is specific to ZSH and won't be fixed here, instead a ZSH parser should be written/used

**Comment by Thanatermesis** [comment]
Just for the record, there's 2 more cases I'm discovering in my BASH source code files that breaks the syntax:

```bash
line="${line#*<title>}"
line="${line%</title>*}"
```

Unfortunately I need to switch from NeoVim to Vim everytime I open a file on which the syntax rendering is broken

**Comment by amaanq** [comment]
Should be fixed soon, thanks
