### ISSUE TITLE
Problem circa bit shift operator

### ISSUE THREAD

**Issue by jcorbin** [tree-sitter/tree-sitter-bash#176]
The current bash treesitter grammar seems to have a problem with the bitshift operator inside a `$(( ... ))` math expression.

At least for me, setup to use treesitter syntax highlighting, the highlighting stops working correctly at such a point:
![image][before_shot]

Where-as removing the `<<` allows highlighting to proceed until it hits the next one:
![image][after_shot]

I don't yet know how to get further info about what the ts ast looks like at those points, or how to further debug what's going on, but here's the [source file][source_file] in question for reference.

[before_shot]: https://github.com/tree-sitter/tree-sitter-bash/assets/49715/ad165888-7296-47f8-847f-49667aae8919
[after_shot]: https://github.com/tree-sitter/tree-sitter-bash/assets/49715/96756ec9-bbb0-43db-b999-198f298386e2

[source_file]: https://github.com/jcorbin/home/blob/9309497accdc0c6c0d3925e43a30d72c44f589ab/.config/river/init#L114

**Comment by jcorbin** [comment]
Ahh okay, progress:
- by the magic of neovim's `vim.treesitter.inspect_tree()`
- looks like the bash grammar is incorrectly, altho understandably in retrospect, confusing bit shift with a heredoc
![image](https://github.com/tree-sitter/tree-sitter-bash/assets/49715/fe221dec-210b-4079-bf26-1a4ca5eb2094)

**Comment by Ordoviz** [comment]
Related: #175
