### ISSUE TITLE
Errors when using semicolon character with substring removal

### ISSUE THREAD

**Issue by bartels** [tree-sitter/tree-sitter-bash#178]
A variable expansion can use substring removal with a pattern to specify what to remove.

For example, using  semicolons in a pattern can remove parts of a string, either from the start or end.

```bash
FOO="this string has semicolons ;that can be ;used with substring removal pattern"

echo "${FOO#*;}"
echo "${FOO##*;}"
echo "${FOO%;*}"
echo "${FOO%%;*}"
```

The above  results in error when the semicolon is encountered inside the variable expansions (on each echo line). Other characters besides semicolon do work find however.

See the `Substring removal` section here: https://github.com/rawiriblundell/wiki.bash-hackers.org/blob/main/syntax/pe.md#substring_removal

**Comment by Ordoviz** [comment]
duplicate of #66
