### ISSUE TITLE
Can't find bash-language-server on your PATH

### ISSUE THREAD

**Issue by niieani** [tree-sitter/tree-sitter-bash#19]
I have `bash-language-server` installed globally, and the global `bin` directory is in `PATH`, declared both in my shell (fish), and other installed shells `.bashrc` and `.zshrc`.

With all this done, I still get a "Can't find bash-language-server on your PATH" error in VSCode.

Could the path to the language server be configurable as a VSCode setting?

**Comment by maxbrunsfeld** [comment]
👍 Closing this out since it’s about bash-language-server, not this library.

**Comment by niieani** [comment]
I opened the issue in the wrong repo! 🤦‍♂️ Sorry about that! Awesome job on the `tree-sitter-bash`, btw.!
