### ISSUE TITLE
Parameter expansion issues

### ISSUE THREAD

**Issue by ObserverOfTime** [tree-sitter/tree-sitter-bash#195]
I think the expansion logic ought to be reworked.

- [ ] `${parameter-default}`
- [ ] `${parameter:-default}`
- [x] `${parameter=default}`
- [ ] `${parameter:=default}`
- [ ] `${parameter+alt_value}`
- [ ] `${parameter:+alt_value}`
- [ ] `${parameter?err_msg}`
- [ ] `${parameter:?err_msg}`
- [x] `${#var}`
- [x] `${var#Pattern}` [^1]
- [x] `${var##Pattern}` [^1]
- [ ] `${var%Pattern}`
- [ ] `${var%%Pattern}`
- [ ] `${var:pos}` [^2]
- [ ] `${var:pos:len}` [^2]
- [ ] `${var/Pattern/Replacement}` [^3]
- [ ] `${var//Pattern/Replacement}` [^3]
- [ ] `${var/#Pattern/Replacement}` [^3]
- [ ] `${var/%Pattern/Replacement}` [^3]
- [x] `${!varprefix*}` [^4]
- [x] `${!varprefix@}` [^4]
- [ ] `${parameter@operator}` [^5]
- [x] `${!parameter}`

See here for details and test cases:
- https://tldp.org/LDP/abs/html/parameter-substitution.html
- https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html

[^1]: `Pattern` is a glob so it should be a `regex` node rather than `word`.
[^2]: `pos` can be negative iff it's preceded by whitespace or wrapped in `()`.
[^3]: Only the first "/" is currently parsed and the rest is considered a `regex`.
[^4]: "*" / "@" are currently parsed as `word`.
[^5]: `operator` must be one of `[UuLQEPAKak]`.

**Comment by ObserverOfTime** [comment]
Most of these seem to be parsed properly if there's whitespace after the punctuation. (e.g. `${parameter- default}
`)

Also, expansions within heredocs are parsed as commands when they should not be.

```bash
cat <<EOF
${parameter- default}
EOF
```

```
0:0  - 3:0     program
0:0  - 0:9       redirected_statement
0:0  - 0:3         body: command
0:0  - 0:3           name: command_name
0:0  - 0:3             word `cat`
0:4  - 0:9         redirect: heredoc_redirect
0:4  - 0:6           "<<"
0:6  - 0:9           heredoc_start `EOF`
0:9  - 1:0       "\n"
1:0  - 1:20      command
1:0  - 1:20        name: command_name
1:0  - 1:20          expansion
1:0  - 1:2             "${"
1:2  - 1:11            variable_name `parameter`
1:11 - 1:19            word `-default`
1:19 - 1:20            "}"
1:20 - 2:0       "\n"
2:0  - 2:3       heredoc_body `EOF`
2:3  - 3:0       "\n"
```

**Comment by amaanq** [comment]
awesome report, will fix it in a bit

**Comment by amaanq** [comment]
Is replacement also a regex?

**Comment by ObserverOfTime** [comment]
> Is replacement also a regex?

No.

> And do the operators need to be immediate?

Do you mean the punctuation or the letter "operators"?

- Whitespace is not allowed in parameter names (i.e. before the punctuation).
- Whitespace is not allowed after `@` in `${parameter@operator}`.
- Whitespace before or after `pos` and `len` is allowed and ignored.
- Other whitespace is considered part of the respective word or regex.

---

Also note that `len` cannot be negative and, while `${parameter: -pos:len}` is valid, Bash ignores the `len` in that case.
