### ISSUE TITLE
Failure to parse subshell inside arithmetic_expansion

### ISSUE THREAD

**Issue by arthurzam** [tree-sitter/tree-sitter-bash#206]
For the following bash code:

```sh
echo "$(( $( ver_cut 2 ) - 1 ))"
```

With tree-sitter-bash at c3c6c2ea26fc1649fd40b1a6c999ae676e91f521 (current master, post 0.20.3) I get a failure:

```
(program (command name: (command_name (word)) argument: (string (arithmetic_expansion (ERROR (heredoc_end)) (binary_expression left: (parenthesized_expression (variable_name) (ERROR (word))) right: (number))))))
```

While with tree-sitter-bash 0.19.0 it parses correctly:

```
(program (command name: (command_name (word)) argument: (string (command_substitution (subshell (command name: (command_name (command_substitution (command name: (command_name (word)) argument: (word)))) argument: (word) argument: (word)))))))
```

**Comment by ahlinc** [comment]
@arthurzam Would it be ok if there [would be no](https://github.com/tree-sitter/tree-sitter-bash/pull/209/files#diff-1ffac96076df3ce95cc2a3ba23448494a6bbb3d027efaf046226bf2af1469bbaR535-R536) the `subshell` node in the `command_substitution` node?

**Comment by arthurzam** [comment]
> @arthurzam Would it be ok if there [would be no](https://github.com/tree-sitter/tree-sitter-bash/pull/209/files#diff-1ffac96076df3ce95cc2a3ba23448494a6bbb3d027efaf046226bf2af1469bbaR535-R536) the `subshell` node in the `command_substitution` node?

As long as no error is generated, fine by me :)

**Comment by ahlinc** [comment]
![image](https://github.com/tree-sitter/tree-sitter-bash/assets/14666676/a0e8f199-5f4e-4d12-bcc4-34e0e23cc846)

@arthurzam awesome! Because the `subshell` node now is dedicated for only braces like on the above screenshot.

**Comment by arthurzam** [comment]
Sounds great, and makes it easier for people to parse. Thanks for working on those.

**Comment by amaanq** [comment]
Is your corpus available on git somewhere? I'm always looking to add more repos to our CI script :)

**Comment by ahlinc** [comment]
> Is your corpus available on git somewhere? I'm always looking to add more repos to our CI script to catch failures :)

@amaanq all `*.ebuild` and `*.eclass` files in https://github.com/gentoo/gentoo are shell scripts.

**Comment by amaanq** [comment]
Wow, cloning Gentoo and parsing all ebuild and eclass files took 8 minutes, with 684 failures out of 28879, what an amazing corpus

**Comment by arthurzam** [comment]
> Wow, cloning Gentoo and parsing all ebuild and eclass files took 8 minutes, with 684 failures out of 28879, what an amazing corpus
> 
> I think once the failures are fixed, we can use this corpus before a release occurs in our CI, having it run during every pr/push would be quite slow

Oh, wow - that would be really great and useful, thank you. Also on our side, I'll add a code, that upon finding an `error` node in the parsed bash code, will request the user to file a bug for our [pkgcheck](https://github.com/pkgcore/pkgcheck), and if verified this indeed fails by me, I'll redirect here.

We are very thankful for this integration!
