### ISSUE TITLE
No handling for arithmetic operators precedence

### ISSUE THREAD

**Issue by ahlinc** [tree-sitter/tree-sitter-bash#208]
```sh
echo "$(( 1 + 2 * 3 ))"
```

![image](https://github.com/tree-sitter/tree-sitter-bash/assets/14666676/ac441dba-acbb-41d2-a856-60252f9f7871)

**Comment by amaanq** [comment]
Yeah good catch, expressions outside of arithmetic_expansions shouldn't have a precedence but these should

**Comment by ahlinc** [comment]
On top of #211 

![image](https://github.com/tree-sitter/tree-sitter-bash/assets/14666676/95a1376c-e4e5-44ac-a099-f3bf0f2bcac9)

The issue still exists, multiplication should be grouped into its own node because it has precedence over addition.

**Comment by ahlinc** [comment]
@amaanq May be in Gentoo repository it would be better to have no parsing errors and do fixes to avoid all complicated cases in the code, but for the parser impl I would ask you to open an issue with all hard parsing cases that are correct bash code, just for visibility of deficiencies and may be we'd figure out later how to handle them too.
