### ISSUE TITLE
Distinguish function_call from command call in command statement

### ISSUE THREAD

**Issue by saccarosium** [tree-sitter/tree-sitter-bash#218]
Hi,
I use a neovim plugin called: [nvim-treesitter-refactor](https://github.com/nvim-treesitter/nvim-treesitter-refactor); It let you smartly rename variable/functions using Treesitter. 

I've been having some problems with renaming functions in shell scripts. I think that the problem is that the parser will not make a distinction between a `function_call` and an 'exectutable' call (e.g. calling `grep` vs calling a user defined function call `great`).

For example, I have the following script:

```sh
greet() {
  echo "Hello"
}

greet
```

The script has the following AST:

```
(function_definition) ; [1:1 - 3:1]
 name: (word) ; [1:1 - 5]
 body: (compound_statement) ; [1:9 - 3:1]
  (command) ; [2:5 - 16]
   name: (command_name) ; [2:5 - 8]
    (word) ; [2:5 - 8]
   argument: (string) ; [2:10 - 16]
    (string_content) ; [2:11 - 15]
(command) ; [5:1 - 5]
 name: (command_name) ; [5:1 - 5]
  (word) ; [5:1 - 5]
```

If I try to rename the function `greet` with `new_name` it will rename the function declaration but not the function calls, creating the following result:

```sh
new_name() {
  echo "Hello"
}

greet
```

**Comment by amaanq** [comment]
wrong repo, post it in nvim-ts-refactor
