### ISSUE TITLE
Three-expression bash for loops syntax

### ISSUE THREAD

**Issue by bunam** [tree-sitter/tree-sitter-bash#22]
failed to parse expression for :
```
for (( i=2 ; i <= n ; i++ )) {
	echo $i
}
```

https://github.com/mads-hartmann/bash-language-server/issues/66

**Comment by bunam** [comment]
hello I have updated and I'm l having a failed to parse expression for "n" but if I correct "<=" by "<" it's OK but I want "<=" 

```
#!/usr/bin/env bash

n=3
for (( i=2 ; i <= n ; i++ )) {
 echo $i
}
```

**Comment by skovhus** [comment]
Thanks. Can you reopen the issue? Or create a new one?
