### ISSUE TITLE
Incorrect highlighting for variable substitution with for string with braces "\{"

### ISSUE THREAD

**Issue by ZiViZiViZ** [tree-sitter/tree-sitter-bash#231]
I've been requested by @lucario387 to report nvim-treesitter/nvim-treesitter#5601 over in this repo instead.
All the details are in the mentioned issue.  LMK, if you need more info.

**Comment by lucario387** [comment]
Maybe just write the issue as regression/... instead?

**Comment by ZiViZiViZ** [comment]
Hi @amaanq,

It looks better now but still not quiet right.
In line 4, `}` that is highlight to match the `${` in `${name%\}}` is part of `\}` but instead, should be the right most `}` just before the closing `"` at the end of the line.

![image](https://github.com/tree-sitter/tree-sitter-bash/assets/95288998/5bd3cfc4-897b-4f5d-8987-412d807c619b)

<details><summary>Code Snippet</summary>

```bash
name="${value#\{sd.cicd.}"
echo "${name%\}}"
```
</details>
