### ISSUE TITLE
Incorrect parsing of (concatenation (simple_expansion) (word)) when word begins with `}`

### ISSUE THREAD

**Issue by aarondill** [tree-sitter/tree-sitter-bash#241]
Given a snippet like `v=$hello}/world` (which assigns the value of hello, followed by the literal `}/world`)
It is parsed as this (using TSPlayground):
```treesitter
program [0, 0] - [1, 0]
  variable_assignment [0, 0] - [0, 15]
    name: variable_name [0, 0] - [0, 1]
    value: concatenation [0, 2] - [0, 15]
      simple_expansion [0, 2] - [0, 8]
        variable_name [0, 3] - [0, 8]
      word [0, 9] - [0, 15]
```

Assuming the concatenation node is stored in `concatNode`:
```js
console.log(concatNode.text) // $hello}/world
console.log(concatNode.namedChildren[0].text) // $hello
console.log(concatNode.namedChildren[0].type) // simple_expansion

console.log(concatNode.namedChildren[1].type) // word
// This should begin with the literal bracket!
console.log(concatNode.namedChildren[1].text) // /world
```

Looking at the start and ending positions, it seems the `}` is mistakenly included in the simple_expansion, but somehow isn't included in it's text value (and shouldn't be!)

**Comment by aarondill** [comment]
the snippet I originally discovered this with was `. $utils}/hello || exit`
Assuming the concatenation node is `node`, running the following testing snippet (I inserted it into `getSourcedPathInfoFromNode`) results in the following output:
<details>
<summary>testing snippet</summary>

```js
  log(`node: ${node}`)
  log(`node.type: ${node?.type}`)
  log(`node.text: ${node?.text}`)
  log(`node.startPosition.column: ${node?.startPosition.column}`)
  log(`node.endPosition.column: ${node?.endPosition.column}`)
  log(``)
  for (let i = 0; i < node.childCount; i++) {
    const child = node.child(i)
    log(`child(${i}): ${child}`)
    log(`child(${i}).type: ${child?.type}`)
    log(`child(${i}).text: ${child?.text}`)
    log(`child(${i}).startPosition.column: ${child?.startPosition.column}`)
    log(`child(${i}).endPosition.column: ${child?.endPosition.column}`)
    log(``)
  }
```
</details>

```log
node: (concatenation (simple_expansion (variable_name)) (word))
node.type: concatenation
node.text: $utils}/hello
node.startPosition.column: 2
node.endPosition.column: 15

child(0): (simple_expansion (variable_name))
child(0).type: simple_expansion
child(0).text: $utils
child(0).startPosition.column: 2
child(0).endPosition.column: 8

child(1): (word)
child(1).type: word
child(1).text: /hello
child(1).startPosition.column: 9
child(1).endPosition.column: 15
```

**Comment by amaanq** [comment]
hm, i cant comment on your js code, but the parse tree output looks good on my end:

![image](https://github.com/tree-sitter/tree-sitter-bash/assets/29718261/6a8d64e8-5104-4379-b064-e17c2f14d684)

**Comment by aarondill** [comment]
You're correct. I'm sorry for wasting your time. 
I was working on a patch for [bash-language-server](https://github.com/bash-lsp/bash-language-server) and came across this issue.
I (mistakenly) believed they were using an up-to-date version of this parser, but it turns out it is *198*(!) commits out of date.

**Comment by amaanq** [comment]
no worries there are so many changes (and more coming soon!), that i cant blame them for not updating yet
