### ISSUE TITLE
Error in parameter expansion when mixing single/double quotes

### ISSUE THREAD

**Issue by savetheclocktower** [tree-sitter/tree-sitter-bash#242]
This construct is valid in bash but does not parse correctly:

```shell
var="${var/'a'*/b}"
```

Here is an explanation from @Tamaranch (who discovered this bug):

 > Replace the first occurrence of `a` followed by anything (i.e. the longest suffix of the form `a*`) with `b` in `$var`. This can be seen as an extension of the POSIX parameter expansion `${var%%a*}` which removes the longest suffix of the form `a*` (i.e. replaces it with nothing).
>
> For reference, the actual lines of code I have locally are the following, but I've tried to extract the simplest example:
>
> ```shell
> curf="${f%'-roff2html'*}.html"
> reff="${f/'-roff2html'*/'-ref'}.html"
> ```
> The first doesn't break highlighting, the second does.
>
> Note that in all these cases, neither single nor double quotes are necessary (double quotes might be if there was concatenation with a string containing spaces, but single quotes never are I think).
>
> However, their use is legal, and it may (or may not) be considered that their use makes the code more readable, particularly with correct highlighting.

**Comment by Tamaranch** [comment]
Just in case or for the sake of completeness, this construct is also valid, doesn't parse correctly either and breaks highlighting in another way (see https://github.com/pulsar-edit/pulsar/issues/873#issuecomment-1900963491):
```sh
var="${var/'a'*/'b'}"
```

**Comment by savetheclocktower** [comment]
@amaanq, this related example still errors:

```bash
reff="${f/'-roff2html'*/'-ref'}.html"
```
