### ISSUE TITLE
document install of tree sitter bash C on windows

### ISSUE THREAD

**Issue by gogo2464** [tree-sitter/tree-sitter-bash#263]
tree sitter bash install has no command on cicd and is not documented.

Could you document it please?

**Comment by gogo2464** [comment]
make all failed because of a lacking grep

**Comment by ObserverOfTime** [comment]
The makefile does not work on windows. You can run `tree-sitter build` to compile the dll.

**Comment by gogo2464** [comment]
Thank you very much. the project seems very serious. Could I have the docs for the full commands and how to generate an ast from bash from tree-sitter-bash please?

**Comment by gogo2464** [comment]
I think there may be a big lack of doc on this project :/

**Comment by gogo2464** [comment]
a full tutorial could be huge!

**Comment by gogo2464** [comment]
@ObserverOfTime latest prs looks good!

I would like to use the library in C. Could you pakcage the library in C please?
