### ISSUE TITLE
0.13.2 missing parsing errors

### ISSUE THREAD

**Issue by skovhus** [tree-sitter/tree-sitter-bash#27]
0.13.1 error on a file like this with a missing `fi`:
```bash
PATH_INPUT=src/in.js
PATH_OUTPUT=src/out.js

if [[ $PATH_INPUT -nt $PATH_OUTPUT ]]; then
  babel --compact false ${PATH_INPUT} > ${PATH_OUTPUT}
f
```

I guess this is a regression from 0.13.1? Didn't investigate if this is due to https://github.com/tree-sitter/tree-sitter-bash/commit/6ff7fe3c7e584b7eaf6b9fb3fe952499d1dd3008

**Comment by maxbrunsfeld** [comment]
Parsing this file with 0.13.2, I get this syntax tree:

```
$ tree-sitter parse test.sh 

(program [0, 0] - [6, 0]
  (variable_assignment [0, 0] - [0, 20]
    (variable_name [0, 0] - [0, 10])
    (word [0, 11] - [0, 20]))
  (variable_assignment [1, 0] - [1, 22]
    (variable_name [1, 0] - [1, 11])
    (word [1, 12] - [1, 22]))
  (if_statement [3, 0] - [6, 0]
    (test_command [3, 3] - [3, 37]
      (binary_expression [3, 6] - [3, 34]
        (simple_expansion [3, 6] - [3, 17]
          (variable_name [3, 7] - [3, 17]))
        (test_operator [3, 18] - [3, 21])
        (simple_expansion [3, 22] - [3, 34]
          (variable_name [3, 23] - [3, 34]))))
    (command [4, 2] - [4, 54]
      (command_name [4, 2] - [4, 7]
        (word [4, 2] - [4, 7]))
      (word [4, 8] - [4, 17])
      (word [4, 18] - [4, 23])
      (expansion [4, 24] - [4, 37]
        (variable_name [4, 26] - [4, 36]))
      (file_redirect [4, 38] - [4, 54]
        (expansion [4, 40] - [4, 54]
          (variable_name [4, 42] - [4, 53]))))
    (command [5, 0] - [5, 1]
      (command_name [5, 0] - [5, 1]
        (word [5, 0] - [5, 1])))))
test.sh	7 ms	MISSING fi [6, 0] - [6, 0]

```

The last child of the `if_statement` is a `fi` token that is "missing" (i.e. tree-sitter realized that it was missing and inserted it for error recovery). I just realized that the `SyntaxNode.isMissing()` method was not declared in the typescript declarations file. That is now fixed.

In `bash-language-server`, I'm guessing you're probably not checking if nodes are missing. These nodes will have zero size (e.g. `startPosition` equals `endPosition`).

**Comment by skovhus** [comment]
No, we were actually just checking if the tree sitter returned the ERROR type. 

Didn’t know the grammar supported error recovery. Really cool. I guess we could use that in bash-language-server to show hints.

**Comment by maxbrunsfeld** [comment]
Another thing that might be useful is that you can check whether a parent node contains any errors of any kind using the `SyntaxNode.hasError()` method. This will return true of the node contains any `ERROR` nodes or any missing nodes.

**Comment by skovhus** [comment]
Thanks! This is really useful. I've created an issue to look into this https://github.com/mads-hartmann/bash-language-server/issues/74

**Comment by maxbrunsfeld** [comment]
Great! I'm going to close this out since I think the parser is behaving correctly in this regard.
