### ISSUE TITLE
Different Highlight Color for command_name and function_definition

### ISSUE THREAD

**Issue by datgausaigon** [tree-sitter/tree-sitter-bash#271]
Hi, 

In bash script `built-in commands, conditional statements and custom functions` should be formatted with 3 different colors.

Currently you are highlight `built-in commands` and `custom functions` (`command_name` and `function_definition`) same color.

This issue also affects a Zed IDE Extension and I posted it on their repository:
https://github.com/d1y/bash.zed/issues/4

We found the code where you define `built-in commands` and `custom functions` (`command_name` and `function_definition`) to define Highlight the same:
Thanks [@hongquan](https://github.com/hongquan) for finding the line of code of the issue.

https://github.com/tree-sitter/tree-sitter-bash/blob/master/queries/highlights.scm
Line 8 and Line 34.

![457702267_1041361457365370_1259341679259196390_n](https://github.com/user-attachments/assets/ae68bce4-9021-4de0-8986-225d7264a96a)

Thanks 🐻

**Comment by amaanq** [comment]
This is a non-issue - Zed highlights are not controlled here, and currently, the highlights are fine as is (upstream's are typically simpler than editor-specific queries), but if you think the highlights *can* objectively be improved then a PR is welcome.
