### ISSUE TITLE
No 2x new line after last command get error "Failed to parse expression"

### ISSUE THREAD

**Issue by bunam** [tree-sitter/tree-sitter-bash#29]
I'm not sure it's mandatory to have bash script ended by 2 newlines

The parser is KO with :
```
#!/usr/bin/env bash

exit 0<newline>
```

The parser is OK with :

```
#!/usr/bin/env bash

exit 0<newline>
<newline>
```

but script 1 run well so...

**Comment by bunam** [comment]
argg

I have something that made the parser KO with only one <newline> and OK with 2 <newline>
I'm trying to determine what is the minimal something...

```
#!/usr/bin/env bash

<something>

exit 0<newline>
```

**Comment by bunam** [comment]
i have a clue 
it's after the corretion of
https://github.com/tree-sitter/tree-sitter-bash/issues/22

and i have a minimal whith parse error :
```
#!/usr/bin/env bash

function toto { : }

exit 0<newline>
```
no parse error but it should show error for the function definition
```
#!/usr/bin/env bash

function toto { : }

exit 0<newline>
<newline>
```

but the 2 aren't good for bash

the good one with 1or 2 newline at the end

```
#!/usr/bin/env bash

function toto { : ; }

exit 0
```

so it's related to one line "function" or "for" definition

**Comment by maxbrunsfeld** [comment]
Some things have changed since you posted this. As far as I can tell, all of the code examples now parse without error, so I'm going to close this out. Let me know if there are still parse errors related to this.
