### ISSUE TITLE
node.isMissing() returns unexpected position

### ISSUE THREAD

**Issue by skovhus** [tree-sitter/tree-sitter-bash#30]
I'm trying to use `node.isMissing()` for improving https://github.com/mads-hartmann/bash-language-server, but the `startPosition` and `endPosition` are off for the `fi` type below. 

Example
```bash
if [[ $PATH_INPUT -nt $PATH_OUTPUT ]]; then
  babel --compact false ${PATH_INPUT} > ${PATH_OUTPUT}
f

echo "test"

```

The missing node will be shown after the `echo` statement, although I would expect it to fail at the position of `f`.

<img width="465" alt="screenshot 2018-08-21 21 28 49" src="https://user-images.githubusercontent.com/1260305/44424379-42864b00-a589-11e8-877d-fafdd31cd732.png">

Any advice how to fix this?

**Comment by maxbrunsfeld** [comment]
The parser can't really tell where the `fi` should go. I think the only way it could guess that it was intended on line 10 is for it to know about formatting conventions like indentation, which it currently isn't aware of.

**Comment by skovhus** [comment]
Thanks for the quick reply. Wondering if we should simply show an error at the top or bottom of the file then with the missing node.

Closing this for now.
