### ISSUE TITLE
heredoc single/double quoted : failed to parse expression 

### ISSUE THREAD

**Issue by bunam** [tree-sitter/tree-sitter-bash#31]
https://en.wikipedia.org/wiki/Here_document#Unix_shells
in this example i wouldn't variable to be replaced

```
#!/usr/bin/env bash

function f2() {

cat << 'EOF' > script.sh
#!/bin/bash
echo $PWD
EOF

}

f2

```

see the error
![image](https://user-images.githubusercontent.com/781793/45061148-85751200-b0a3-11e8-82df-ff1ad99bfa1c.png)

**Comment by thegranddesign** [comment]
I have a couple more HEREDOC issues:

![image](https://user-images.githubusercontent.com/17790097/46307792-8d7a8180-c57d-11e8-9822-062ce6758f3b.png)

![image](https://user-images.githubusercontent.com/17790097/46307818-9d926100-c57d-11e8-9992-a0e28f507fe2.png)

[Gist](https://gist.github.com/thegranddesign/bb94d62efbf86c13b1b7fc4f4ee64af2)
