### ISSUE TITLE
Error parsing expressions containing non comment '#'

### ISSUE THREAD

**Issue by simonfxr** [tree-sitter/tree-sitter-bash#41]
Found these corner cases while using [bash-language-server](https://github.com/mads-hartmann/bash-language-server). The parser fails on some expressions where '#' should not be interpreted as the start of a comment.
Examples:
- Interpret number in a certain base: `dec=$((10#$x))`
- Referring to the number of positional parameters : `last=${!#}`, `n=${#}`.

**Comment by tterranigma** [comment]
I think the issue is with general variable expansions. For instance, the following also fail:

```
q="${a1%)}"
characters="${2-\\{\}[]().}"
```
