### ISSUE TITLE
Variables in functions missing type

### ISSUE THREAD

**Issue by akurtakov** [tree-sitter/tree-sitter-bash#42]
First of all sorry if the report is not detailed enough. I've been asked to report it here by [bash-language server](https://github.com/mads-hartmann/bash-language-server) author . So variables in functions like:
```sh
#!/bin/sh
# A simple script with a function...

add_a_user()
{
  USER=$1
  PASSWORD=$2
  shift; shift;
  # Having shifted twice, the rest is now comments ...
  COMMENTS=$@
  echo "Adding user $USER ..."
  echo useradd -c "$COMMENTS" $USER
  echo passwd $USER $PASSWORD
  echo "Added user $USER ($COMMENTS) with pass $PASSWORD"
}

###
# Main body of script starts here
###
echo "Start of script..."
add_a_user bob letmein Bob Holness the presenter
add_a_user fred badpassword Fred Durst the singer
add_a_user bilko worsepassword Sgt. Bilko the role model
echo "End of script..."

```
are missing something from grammar side as indicated to me in https://github.com/mads-hartmann/bash-language-server/issues/101 . 
Please let me know how I can help in mediating the conversation between the two projects I'm not developer of so the issue gets resolved.

**Comment by maxbrunsfeld** [comment]
I responded to the original language server issue. I'm going to close this out because I believe the parser is working correctly. Sorry for the back-and-forth.
