### ISSUE TITLE
How to use this parser in the main tree-sitter?

### ISSUE THREAD

**Issue by AlterX76** [tree-sitter/tree-sitter-bash#49]
Hello, documentation is really fuzzy regarding how to use specific language parser functions. Is describing example code, what is doing but not how to integrate a plugin and easily use it. Moreover, I use the suggestion to just add source code and header to my project, but I don't understand how I can do the same for the bash parser. I think it is really appreciated to have a doc describing this in details, also to spread the use of this nice project.
Thanks

**Comment by Arcanemagus** [comment]
The documentation has an [example program](http://tree-sitter.github.io/tree-sitter/using-parsers#an-example-program) that goes over how to integrate `tree-sitter-json`, you should be able to just change the name to get a basic client.

**Comment by AlterX76** [comment]
I have tried this example and compiler keeps telling me the parser json
doens t exist

**Comment by maxbrunsfeld** [comment]
For that command to work, you need to have [tree-sitter-json](https://github.com/tree-sitter/tree-sitter-json), which is linked at the beginning of the section.

**Comment by maxbrunsfeld** [comment]
I'm closing this out because it doesn't have to do with `tree-sitter-bash`. I also think that the documentation page that @Arcanemagus linked spells out how to use the C library pretty concretely. You do need to have some familiarity with compiling C programs to use the C library directly.

**Comment by AlterX76** [comment]
I am a software developer and it is not a problem on how compile the
example that works, it is not describede in any place how I can integrate
the json or whatever plugin in the example.

Il giorno mer 22 mag 2019 alle ore 20:25 Max Brunsfeld <
notifications@github.com> ha scritto:

**Comment by Arcanemagus** [comment]
I haven't attempted it myself, but from the documentation I believe these to be the relevant parts:
![image](https://user-images.githubusercontent.com/427137/58272502-8938e980-7d43-11e9-96f8-2d4852023ca3.png)

![image](https://user-images.githubusercontent.com/427137/58272550-ac639900-7d43-11e9-8940-f947ed48962c.png)

**Comment by AlterX76** [comment]
Hi,
thanks some how I overlooked this, but compilingadding that parser.c I get:
[image: image.png]

So if just a file is required I don't understand why those are not just
grouped in a directory under the main tree-sitter?

Thanks any way for the help
Gianni

Il giorno gio 23 mag 2019 alle ore 19:15 Landon Abney <
notifications@github.com> ha scritto:
