### ISSUE TITLE
parse error when negating a variable assignment in an if statement

### ISSUE THREAD

**Issue by spikegrobstein** [tree-sitter/tree-sitter-bash#51]
I was sent over here after filing this issue: https://github.com/mads-hartmann/bash-language-server/issues/135

I'm getting a parse error when I have an `if` statement where I negate a variable assignement. For example:

```bash
#! /usr/bin/env bash

bar() {
  return 1
}

foo=''

if ! foo="$(bar)"; then # <-- Syntax error: expected "word" somewhere in the file
  echo "ok."
fi
```

The error message in the comment is coming from the language server that's implementing your library.

Hopefully this is enough info for a fix. thanks so much!

**Comment by beltaurus** [comment]
I have the same issue: it seems like the parser is expecting a Simple Command, where we start with some assignments with local scope, followed by a command (word). However, if there is no word, then we simply have an assignment, and follow the rules of exit code for such assignments.
In my case, the exit code should be extracted from command substitution:

```
if ! _exe=$(command -v dummy); then
  echo "Dummy command does not exist"
fi

```
The false error goes away when we're taking away the expression negation (!)... so a work around is:

```
if _exe=$(command -v dummy); then
  ...
else
  echo "Dummy command does not exist"
fi
```
But that's just not practical in all scenarios.

**Comment by spikegrobstein** [comment]
Luckily I’m just using this in my editor so I’m living with the errors. I don’t want to go add no-op handlers for the successful situations especially if this gets fixed and I can switch back.
