### ISSUE TITLE
Unable to parse ${#}

### ISSUE THREAD

**Issue by Hologos** [tree-sitter/tree-sitter-bash#57]
I am having similar issue as #21. Sample code:

```bash
if [[ ${#} -ne 3 ]]; then
    tpcp::utils::usage
    tpcp::utils::terminate
fi
```

![Snímek obrazovky 2019-08-24 v 16 32 24](https://user-images.githubusercontent.com/1620004/63638803-051d3780-c68d-11e9-9c38-d7d35b9306c8.png)

**Comment by Tatsh** [comment]
My issue of not being able to use these expressions might be related:

```sh
filename=${filename##+( )}
filename=${filename%%+( )}
```

https://github.com/mads-hartmann/bash-language-server/issues/152
