### ISSUE TITLE
Parse error for here document inside an if with variable 

### ISSUE THREAD

**Issue by skovhus** [tree-sitter/tree-sitter-bash#61]
Parse fails for the entire document when you have a here document inside an `if`, that contains a variable as the first expression.

MWE:
```bash
if true; then
  a_string='some stuff to cat'
  cat <<XXX
${a_string}
XXX
fi
```

The issue does not occur if:
- not inside an `if`
- there is anything except newlines before `${a_string}`, including whitespace

---

Origin: https://github.com/mads-hartmann/bash-language-server/issues/136

**Comment by deedf** [comment]
Also fails with `for` :

```bash
for a in b c d; do
     read NAME <<EOF
${a}
EOF
done
```

**Comment by deedf** [comment]
Also fails within function definitions.

**Comment by brandonkal** [comment]
It also fails everywhere.

**Comment by skovhus** [comment]
This seems to have been fixed in the newer version of the grammar
