### ISSUE TITLE
"failed to parse expression" with semicolon or parens inside variable expansion

### ISSUE THREAD

**Issue by BenFradella** [tree-sitter/tree-sitter-bash#66]
![image](https://user-images.githubusercontent.com/43310279/68704745-6baa4700-0552-11ea-8eb9-b56040f623ba.png)

From the manjaro bashrc

**Comment by cdar** [comment]
I have something similar

```
case "$TERM" in
xterm* | rxvt*)
	PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
	;;
*) ;;
esac
```

Sorry if it's not the same error.
