### ISSUE TITLE
Failed to parse expression ${#}

### ISSUE THREAD

**Issue by hoijui** [tree-sitter/tree-sitter-bash#77]
The code snippet below generates _Failed to parse expression_ error.

```bash
if [[ ${#} -eq 0 ]]; then
    :
fi
```

There is a [related bash-language-server issue](
https://github.com/bash-lsp/bash-language-server/issues/159).

**Comment by skovhus** [comment]
This seems to have been fixed in the newer version of the grammar.

**Comment by hoijui** [comment]
Indeed, thank you @skovhus ! :-)
