### ISSUE TITLE
Failed to parse expression 'echo $(((duedatesec-todaysec)/86400))'

### ISSUE THREAD

**Issue by paapereira** [tree-sitter/tree-sitter-bash#87]
I'm getting a "Failed to parse expression" in a shell script while calculating the number days between two dates in seconds.

The expression and the shell script execute without any errors.

It was suggested to me that this may be a tree-sitter issue. If it is not I'm sorry in advance.

![image](https://user-images.githubusercontent.com/2096208/83504798-d73b0e00-a4bc-11ea-8a35-69c6111bb0e4.png)

**Comment by TravonteD** [comment]
@paapereira I tried the snippet provided. it looks like `duedatesec-todaysec` is considered a single node. When I separate them with spaces `duedatesec - todaysec`. I get the correct parsing.

**Comment by paapereira** [comment]
Sorry, I'm having the same message.
Did you do it like this?

![2020-07-21_20-31](https://user-images.githubusercontent.com/2096208/88098199-4b2a9600-cb91-11ea-9b3a-2fb4cd282e5e.png)

**Comment by TravonteD** [comment]
yes that's exactly what I did. Can you give more information about your setup? Maybe that would shed some light on possible causes
