### ISSUE TITLE
Parse fails with here doc

### ISSUE THREAD

**Issue by brandonkal** [tree-sitter/tree-sitter-bash#88]
Put simply, it doesn't appear that Here documents are supported.
Example script that fails to parse. Shellcheck has no issue with this.
~~~bash
#!/bin/sh
{
  yaegi
} <<'```'
package main
import "fmt"

func main() {
	fmt.Println("Hello from Go")
}
```
~~~

**Comment by paescuj** [comment]
Same with [here strings](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Here-Strings).
